id: app
title: Test2
type: project
version: 0.1
icon: app.png
introduction:
  format: markdown
  template: |
    Use this app to achieve compliance.
input: []
catalog:
  category: Hologic
  vendor: Hologic
  vendor_url: http://hologic.com
  status: stub
  source_url: https://github.com/mjhillyer/flow-SBD
  description:
    short: Modules for managing Secure by Design activities.
        long: >
          Edit this Markdown file to provide a long description of your compliance app.
          The contents of this file will be displayed in the GovReady-Q Compliance Apps
          Catalog.
questions:
- id: module_1
  title: Secure Engineering Foundations
  type: module
  module-id: module_1
- id: module_2
  title: Environmental and Design Risk Analysis
  type: module
  module-id: module_2
- id: module_3
  title: Threat Modeling
  type: module
  module-id: module_3
- id: module_4
  title: Privacy and Data Risk Analysis
  type: module
  module-id: module_4
- id: module_5
  title: Security Requirements and Controls
  type: module
  module-id: module_5
- id: module_6
  title: 3rd Party Component Risk Management
  type: module
  module-id: module_6
- id: module_7
  title: Product Concept Technical Design Review
  type: module
  module-id: module_7
- id: module_8
  title: Security Testing
  type: module
  module-id: module_8
- id: module_9
  title: Product Security Risk Assessment Summary
  type: module
  module-id: module_9
- id: module_10
  title: Product Documentation
  type: module
  module-id: module_10
